# Define color variables
color_bg="{{colors.primary.default.hex}}"
color_fg="{{colors.on_primary.default.hex}}"
%hidden color0="{{colors.surface.default.hex}}"
%hidden color1="{{colors.error.default.hex}}"
%hidden color2="{{colors.tertiary.default.hex}}"
%hidden color3="{{colors.secondary.default.hex}}"
%hidden color4="{{colors.primary.default.hex}}"
%hidden color7="{{colors.on_surface.default.hex}}"
%hidden color8="{{colors.surface_variant.default.hex}}"
%hidden color15="{{colors.on_surface_variant.default.hex}}"
