# Define color variables
color_bg="#8bd0ef"
color_fg="#003546"
%hidden color0="#0f1417"
%hidden color1="#ffb4ab"
%hidden color2="#c6c2ea"
%hidden color3="#b4cad6"
%hidden color4="#8bd0ef"
%hidden color7="#dfe3e7"
%hidden color8="#40484c"
%hidden color15="#c0c8cd"
