# Define color variables
%hidden color_bg="#03040A"
%hidden color_fg="#D5CBFF"
%hidden color0="#04050C"
%hidden color1="#08156E"
%hidden color2="#463F7B"
%hidden color3="#1533AD"
%hidden color4="#5A61DA"
%hidden color7="#C8BEFF"
%hidden color8="#8379C7"
%hidden color15="#DBD6F7"
