$cursor = rbg(B4A6AD)
$foreground = rgb(FFBA86)
$background = rgb(02040A)
$color0 = rgb(03060C)
$color1 = rgb(172339)
$color2 = rgb(504F66)
$color3 = rgb(1F416E)
$color5 = rgb(6892D5)
$color6 = rgb(C68051)
$color7 = rgb(F9AB79)
$color8 = rgb(AF6D40)
$color9 = rgb(172339)
$color10 = rbg(1F416E)
$color11 = rbg(1F416E)
$color12 = rbg(4D6CA1)
$color13 = rbg(6892D5)
$color14 = rbg(C68051)
$color15 = rbg(F3CDB3)
