$cursor = rbg(AAA4EE)
$foreground = rgb(D5CBFF)
$background = rgb(03040A)
$color0 = rgb(04050C)
$color1 = rgb(08156E)
$color2 = rgb(463F7B)
$color3 = rgb(1533AD)
$color5 = rgb(7F7DDD)
$color6 = rgb(A298E8)
$color7 = rgb(C8BEFF)
$color8 = rgb(8379C7)
$color9 = rgb(08156E)
$color10 = rbg(1533AD)
$color11 = rbg(1533AD)
$color12 = rbg(5A61DA)
$color13 = rbg(7F7DDD)
$color14 = rbg(A298E8)
$color15 = rbg(DBD6F7)
